import json
import os
import subprocess
import sys
import time
from pathlib import Path

import pytest

import analyze_code as ac
import score_evidence as se

SCRIPTS = Path(__file__).resolve().parent.parent / "scripts"


def repo(tmp_path, files: dict, name="proj") -> Path:
    root = tmp_path / name
    for rel, content in files.items():
        path = root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    return root


def ids(result: dict) -> dict:
    return {e["id"]: e for e in result["evidence"]}


def narrating_module(n=60):
    out = ["import os", ""]
    for i in range(n):
        out += [f"def func_{i}(value_{i}):", f"    # Initialize the result list", "    result = []", f"    # Loop through the value_{i} items", f"    for item in value_{i}:", "        # Append the item to the result", "        result.append(item)", "    return result", ""]
    return "\n".join(out)


def human_module(n=70):
    out = ["import os", ""]
    for i in range(n):
        out += [f"def f{i}(x):", "    r = []", "    for y in x:", "        if y % 3:", "            r.append(y * 2)", "    return r", ""]
    return "\n".join(out)


def documented_module(n=14):
    out = []
    for i in range(n):
        out += [f"def helper_{i}(a, b):", '    """Add two values.', "", "    Args:", "        a: first", "        b: second", "", "    Returns:", "        The sum.", '    """', "    return a + b", ""]
    return "\n".join(out * 1) + "\n" + human_module(40)


# --- residue ----------------------------------------------------------------------------------------

def test_assistant_configuration_files_point_to_assistance_not_authorship(tmp_path):
    root = repo(tmp_path, {"CLAUDE.md": "rules", ".cursor/rules/a.mdc": "x", "src/app.py": "print(1)\n"})
    item = ids(ac.analyze(root))["cd-ai-tool-files"]
    assert item["claim"] == "ai_edited" and item["weight"] == 0.8 < se.CONCLUSIVE and "CLAUDE.md" in item["where"]
    assert "cd-ai-tool-files" not in ids(ac.analyze(repo(tmp_path, {"src/app.py": "print(1)\n"}, "clean")))


def test_a_symlinked_assistant_file_is_not_followed_or_counted(tmp_path):
    root = repo(tmp_path, {"src/app.py": "print(1)\n"})
    (root / "CLAUDE.md").symlink_to(tmp_path / "somewhere")
    assert "cd-ai-tool-files" not in ids(ac.analyze(root))


def test_placeholders_in_real_comments_count_but_the_same_text_in_strings_does_not(tmp_path):
    hit = repo(tmp_path, {"a.py": "def f():\n    pass\n\n# ... rest of the code remains the same\n"}, "hit")
    assert ids(ac.analyze(hit))["cd-llm-placeholders"]["weight"] == 0.6
    js = repo(tmp_path, {"a.js": "function f() {}\n// rest of the file remains unchanged\n"}, "js")
    assert "cd-llm-placeholders" in ids(ac.analyze(js))
    # a detector, a linter or a test fixture that merely *contains* the phrase must not be flagged
    safe = repo(tmp_path, {"d.py": 'PATTERN = re.compile(r"# rest of the code remains the same")\nTEXT = "// your code here"\nDOC = """... rest of the code ..."""\n'}, "safe")
    assert "cd-llm-placeholders" not in ids(ac.analyze(safe))


def test_source_markers_need_a_declaration_not_a_mention_of_an_ai_service(tmp_path):
    decl = repo(tmp_path, {"a.py": "# This code was generated by ChatGPT\nx = 1\n"}, "decl")
    assert ids(ac.analyze(decl))["cd-source-markers"]["claim"] == "ai_edited"
    header = repo(tmp_path, {"a.py": "# Written with Copilot\nx = 1\n"}, "hdr")
    assert "cd-source-markers" in ids(ac.analyze(header))
    app = repo(tmp_path, {"a.py": "\n" * 40 + "# the reply is generated by OpenAI and cached\nx = 1\n"}, "app")
    assert "cd-source-markers" not in ids(ac.analyze(app))


def test_chat_reply_comments_and_markdown_fences(tmp_path):
    reply = repo(tmp_path, {"a.py": "# Here's the updated code\nx = 1\n"}, "reply")
    assert "cd-chat-reply-comments" in ids(ac.analyze(reply))
    fenced = repo(tmp_path, {"a.py": "```python\nx = 1\n```\n"}, "fenced")
    assert ids(ac.analyze(fenced))["cd-markdown-fences"]["weight"] == 0.7
    doc = repo(tmp_path, {"a.py": "x = 1\n" * 10 + '"""Example:\n```python\ny = 2\n```\n"""\n' + "z = 3\n" * 10}, "doc")
    assert "cd-markdown-fences" not in ids(ac.analyze(doc))
    md = repo(tmp_path, {"README.md": "```\nx\n```\n", "a.py": "x = 1\n"}, "md")
    assert "cd-markdown-fences" not in ids(ac.analyze(md))


def test_readme_residue_is_reused_and_capped(tmp_path):
    root = repo(tmp_path, {"README.md": "# Tool\n\nSee 【4:0†source】 for more. As an AI language model, I cannot say.\n", "a.py": "x = 1\n"})
    found = ids(ac.analyze(root))
    assert found["cd-readme-citation-markers"]["claim"] == "ai_edited" and found["cd-readme-citation-markers"]["weight"] <= 0.7
    assert found["cd-readme-assistant-phrases"]["where"] == "README.md"
    emoji = repo(tmp_path, {"README.md": "# 🚀 Fast\n## ✨ Features\n## 📦 Install\n", "a.py": "x = 1\n"}, "emoji")
    assert "cd-readme-emoji-headings" in ids(ac.analyze(emoji))


# --- style ------------------------------------------------------------------------------------------

def test_narrating_comments_are_flagged_but_plain_code_leans_the_other_way(tmp_path):
    result = ac.analyze(repo(tmp_path, {"a.py": narrating_module()}, "n"))
    assert ids(result)["cd-narrating-comments"]["score"] >= 6 and ids(result)["cd-narrating-comments"]["weight"] <= 0.12
    plain = ids(ac.analyze(repo(tmp_path, {"a.py": human_module(100)}, "h")))
    assert plain["cd-narrating-comments"]["score"] < 5


def test_docstring_uniformity_uses_the_syntax_tree_and_never_runs_the_code(tmp_path):
    marker = tmp_path / "RAN"
    code = f"import pathlib\npathlib.Path({str(marker)!r}).write_text('x')\n" + documented_module()
    result = ac.analyze(repo(tmp_path, {"a.py": code}, "d"))
    assert "cd-docstring-uniformity" in ids(result) and not marker.exists()


def test_small_projects_skip_style_and_say_why(tmp_path):
    result = ac.analyze(repo(tmp_path, {"a.py": "print(1)\n"}, "s"))
    assert "cd-skipped" in ids(result) and "cd-narrating-comments" not in ids(result)


def test_step_comments_emoji_and_informal_comments(tmp_path):
    code = human_module(60) + "\n".join(f"# Step {i}: do it" for i in range(1, 5)) + "\nprint('✅ done')\n" * 6 + "# hack: wtf\n# TODO(sam) fix\n# FIXME(kim) later\n"
    found = ids(ac.analyze(repo(tmp_path, {"a.py": code}, "x")))
    assert "cd-step-comments" in found and "cd-emoji-in-code" in found and found["cd-informal-comments"]["score"] < 5


def test_plain_symbols_that_every_cli_uses_are_not_emoji(tmp_path):
    code = human_module(60) + "print('✔ ok ✖ no ◆ item')\n" * 8
    assert "cd-emoji-in-code" not in ids(ac.analyze(repo(tmp_path, {"a.py": code}, "sym")))


def test_generated_code_is_reported_and_left_out_of_the_statistics(tmp_path):
    gen = "// Code generated by protoc-gen-go. DO NOT EDIT.\n" + "\n".join(f"// Initialize the field {i}\nvar f{i} = {i}" for i in range(400))
    result = ac.analyze(repo(tmp_path, {"pb.go": gen, "main.go": "package main\nfunc main() {}\n"}, "g"))
    assert ids(result)["cd-generated-code-headers"]["weight"] == 0 and "cd-narrating-comments" not in ids(result)


def test_other_languages_get_comment_statistics(tmp_path):
    js = "\n".join(f"// Initialize the counter {i}\nlet counter{i} = 0;" for i in range(260))
    assert "cd-narrating-comments" in ids(ac.analyze(repo(tmp_path, {"a.js": js}, "js")))


# --- git log ----------------------------------------------------------------------------------------

def log_record(sha, date, subject, body="", added=10):
    return f"\x1e{sha}\x1f{date}\x1f{subject}\x1f{body}\x1d\n\n{added}\t0\tfile.py\n"


def test_commit_trailers_are_reported_by_tool_name_and_never_by_person(tmp_path):
    root = repo(tmp_path, {"a.py": "x = 1\n"})
    records = [log_record(f"{i:040x}", f"2025-01-0{i % 9 + 1}T10:00:00+00:00", f"feat: thing {i}",
                          "Body.\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)\n\nCo-Authored-By: Claude <noreply@anthropic.com>" if i < 6 else "Body.") for i in range(8)]
    result = ac.analyze(root, "".join(records))
    found = ids(result)
    item = found["cd-commit-trailers"]
    assert item["claim"] == "ai_edited" and item["weight"] == 0.9 and "6 of 8" in item["title"]["en"] and "claude" in item["title"]["en"].lower()
    assert found["cd-commit-trailers-share"]["claim"] == "generated"
    assert "noreply" not in json.dumps(result) and "anthropic.com" not in json.dumps(result)


def test_history_shape_bursts_and_messy_history(tmp_path):
    root = repo(tmp_path, {"a.py": "x = 1\n"})
    dump = ac.analyze(root, log_record("a" * 40, "2025-01-01T10:00:00+00:00", "initial commit", added=3000) + log_record("b" * 40, "2025-01-02T10:00:00+00:00", "tweak", added=20))
    assert "cd-history-shape" in ids(dump)
    burst = "".join(log_record(f"{i:040x}", f"2025-01-01T10:{i // 30:02d}:{(i * 2) % 60:02d}+00:00", f"change {i}", added=5) for i in range(30))
    assert "cd-history-bursts" in ids(ac.analyze(root, burst))
    messy = "".join(log_record(f"{i:040x}", f"2025-01-{i % 28 + 1:02d}T10:00:00+00:00", ["wip", "fix typo", "update", "add parser"][i % 4], added=5) for i in range(20))
    assert ids(ac.analyze(root, messy))["cd-messy-history"]["score"] < 5


def test_uniform_long_conventional_commits(tmp_path):
    root = repo(tmp_path, {"a.py": "x = 1\n"})
    log = "".join(log_record(f"{i:040x}", f"2025-02-{i + 1:02d}T10:00:00+00:00", f"feat(core): add part {i}", "word " * 60, added=40) for i in range(12))
    assert "cd-commit-style" in ids(ac.analyze(root, log))


@pytest.mark.parametrize("log", ["", "garbage", "\x1e\x1f\x1d", "\x1e" * 20000, "\x1eabc\x1fnot-a-date\x1fsubject\x1fbody\x1d\nx\ty\tz\n"])
def test_malformed_logs_do_not_crash(tmp_path, log):
    assert isinstance(ac.analyze(repo(tmp_path, {"a.py": "x = 1\n"}), log)["evidence"], list)


def test_no_log_means_history_is_listed_as_not_checked(tmp_path):
    result = ac.analyze(repo(tmp_path, {"a.py": "x = 1\n"}))
    assert any("no git log supplied" in x["en"] for x in result["coverage"]["not_checked"])
    assert not any("no git log supplied" in x["en"] for x in ac.analyze(repo(tmp_path, {"a.py": "x = 1\n"}, "y"), "")["coverage"]["not_checked"])


# --- hostile input ------------------------------------------------------------------------------------

def test_deeply_nested_python_binary_files_and_loops_do_not_crash_or_hang(tmp_path):
    files = {"deep.py": "x = " + "(" * 6000 + "1" + ")" * 6000 + "\n", "bad.py": "def (:\n", "null.py": "x = 1\n\x00\n" * 10, "big.py": "x = 1\n" * 200000}
    root = repo(tmp_path, files)
    (root / "loop").symlink_to(root)
    start = time.time()
    result = ac.analyze(root)
    assert time.time() - start < 30 and isinstance(result["evidence"], list)


def test_file_and_size_limits_are_respected(tmp_path, monkeypatch):
    monkeypatch.setattr(ac, "MAX_FILES", 5)
    root = repo(tmp_path, {f"m{i}.py": "x = 1\n" for i in range(20)})
    result = ac.analyze(root)
    assert result["file"]["files"] == 5 and any("limit was reached" in x["en"] for x in result["limits"])


def test_a_single_file_can_be_analysed(tmp_path):
    root = repo(tmp_path, {"one.py": narrating_module()})
    result = ac.analyze(root / "one.py")
    assert result["file"]["name"] == "one.py" and "cd-narrating-comments" in ids(result)


def test_vendor_directories_are_skipped(tmp_path):
    root = repo(tmp_path, {"node_modules/x/a.js": "\n".join(f"// Initialize {i}\nlet a{i} = 1;" for i in range(200)), "src/a.py": "x = 1\n"})
    assert ac.analyze(root)["file"]["files"] == 1


def test_author_names_never_reach_the_output(tmp_path):
    root = repo(tmp_path, {"a.py": "x = 1\n"})
    log = "\x1e" + "c" * 40 + "\x1f2025-01-01T10:00:00+00:00\x1fSubject\x1fCo-authored-by: Copilot <copilot@github.com>\x1d\n\n1\t0\ta.py\n"
    dumped = json.dumps(ac.analyze(root, log))
    assert "copilot@github.com" not in dumped and "copilot" in dumped.lower()


# --- CLI and scoring integration ----------------------------------------------------------------------

def run(*args):
    return subprocess.run([sys.executable, str(SCRIPTS / "analyze_code.py"), *map(str, args)], capture_output=True, text=True, timeout=120)


def test_cli_refuses_to_overwrite_missing_paths_and_bad_extensions(tmp_path):
    root = repo(tmp_path, {"a.py": "x = 1\n"})
    out = tmp_path / "e.json"
    assert run(root, "--out", out).returncode == 0 and run(root, "--out", out).returncode != 0
    assert run(root, "--out", out, "--force").returncode == 0 and run(root, "--out", tmp_path / "x.txt").returncode != 0
    assert run(tmp_path / "nope").returncode != 0 and run(root, "--git-log", tmp_path / "nope.txt").returncode != 0


def test_code_report_uses_code_wording_the_notice_and_the_style_cap(tmp_path):
    root = repo(tmp_path, {"a.py": narrating_module() + "\n".join(f"# Step {i}: x" for i in range(1, 6)) + "\nprint('✅ ok')\n" * 6, "CLAUDE.md": "rules"})
    evidence = tmp_path / "e.json"
    assert run(root, "--out", evidence).returncode == 0
    report = tmp_path / "r.html"
    done = subprocess.run([sys.executable, str(SCRIPTS / "score_evidence.py"), str(evidence), "--out", str(report), "--lang", "en"], capture_output=True, text=True)
    assert done.returncode == 0, done.stderr
    html = report.read_text(encoding="utf-8")
    assert "Largely written by AI?" in html and "Built with AI assistance?" in html and "Code measurements" in html
    assert "Using AI to write code is normal and legitimate" in html and "does not accuse anyone" in html and "<script" not in html
    summary = json.loads(done.stdout)
    assert summary["assessment"]["ai_edited"]["score"] >= 8                       # the config file decides the "assisted" question
    assert summary["assessment"]["generated"]["confidence"] in ("low", "very_low")   # style alone stays weak
    es = subprocess.run([sys.executable, str(SCRIPTS / "score_evidence.py"), str(evidence), "--out", str(tmp_path / "r_es.html")], capture_output=True, text=True)
    assert "¿Hecho con ayuda de IA?" in (tmp_path / "r_es.html").read_text(encoding="utf-8") and es.returncode == 0


def test_text_inside_the_code_is_escaped_in_the_report(tmp_path):
    root = repo(tmp_path, {"a.py": "# This code was generated by ChatGPT <script>alert(1)</script>\nx = 1\n"})
    html = se.render(se.build_report(ac.analyze(root), []), "en")
    assert "<script>alert" not in html


def test_docs_list_every_code_evidence_id():
    source = (SCRIPTS / "analyze_code.py").read_text(encoding="utf-8")
    found = set(__import__("re").findall(r'ev\("(cd-[a-z-]+)"', source))
    docs = (SCRIPTS.parent / "references/code-signals.md").read_text(encoding="utf-8")
    assert len(found) >= 15 and not {i for i in found if f"`{i}`" not in docs} and "`cd-readme-*`" in docs
